services:
  app:
    build: .
    ports:
      - "${HOST}:${PORT}:${PORT}"
    depends_on:
      - memcached
    environment:
      - HOST=0.0.0.0 # Keep this 0.0.0.0 for Express
      - PORT=${PORT}
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=${MEMCACHED_PORT}
      - MEMCACHED_NAMESPACE=${MEMCACHED_NAMESPACE}
      - REFRESH_TOKENS=${REFRESH_TOKENS}
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  memcached:
    image: memcached
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
